import { defineConfig, devices } from '@playwright/test'
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'

/**
 * Playwright config — web template.
 *
 * Principles:
 *   - LEAN suite: product smoke + critical, no broad coverage.
 *   - Anti-flakiness: retries in CI, locator-based, generous timeouts.
 *   - Storage state reuse: login done once in globalSetup; specs inherit the session.
 *   - Chromium-only in the MVP (Firefox/WebKit when needed, to save CI time).
 *
 * How to run:
 *   pnpm test:e2e         — headless, parallel
 *   pnpm test:e2e:ui      — interactive UI (visual debug)
 *   pnpm test:e2e:debug   — headed mode + debugger
 *   pnpm test:e2e:install — installs Chromium (once)
 *
 * Adapt:
 *   - globalSetup: copy e2e/fixtures/global-setup.ts.example → global-setup.ts
 *   - critical/login.spec: copy e2e/critical/login.spec.ts.example → login.spec.ts
 *   - Add critical/<your-feature>.spec.ts for your product's critical flow
 */

// Loads .env.local manually (Next only loads it in the webServer; the Playwright process would not
// see E2E_USER_EMAIL/E2E_USER_PASSWORD otherwise). Inline parser with no new dependency.
function loadEnvLocal() {
  const envPath = path.join(__dirname, '.env.local')
  if (!existsSync(envPath)) return
  const content = readFileSync(envPath, 'utf8')
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    let value = trimmed.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    if (process.env[key] === undefined) process.env[key] = value
  }
}
loadEnvLocal()

// Where to store the authenticated session reused by the specs.
const STORAGE_STATE_PATH = path.join(__dirname, 'e2e', '.auth', 'storage-state.json')

const BASE_URL = process.env.E2E_BASE_URL || 'http://localhost:3000'
const isCI = !!process.env.CI

// globalSetup only exists once the consumer adapts the .example file.
// Detecting it dynamically avoids a "Cannot find file" error before adaptation.
const GLOBAL_SETUP_PATH = path.join(__dirname, 'e2e', 'fixtures', 'global-setup.ts')
const hasGlobalSetup = existsSync(GLOBAL_SETUP_PATH)

export default defineConfig({
  testDir: './e2e',
  // Only .spec.ts inside e2e/. Unit tests (vitest) live in src/.
  testMatch: /.*\.spec\.ts$/,

  // Generous timeouts to absorb Next cold start + external APIs.
  timeout: 30_000,
  expect: { timeout: 10_000 },

  // CI: controlled parallelism so the runner is not saturated; local: full speed.
  workers: isCI ? 2 : undefined,
  fullyParallel: true,

  // CI retries flakes twice; local 0 to catch non-deterministic tests early.
  retries: isCI ? 2 : 0,

  // Fails the build if a committed .only exists (no leaked focus between PRs).
  forbidOnly: isCI,

  reporter: isCI
    ? [['list'], ['html', { open: 'never', outputFolder: 'playwright-report' }]]
    : [['list']],

  use: {
    baseURL: BASE_URL,
    // Captures trace only on retry — saves time/space, while debugging stays easy when needed.
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    actionTimeout: 10_000,
    navigationTimeout: 30_000,
  },

  ...(hasGlobalSetup ? { globalSetup: './e2e/fixtures/global-setup.ts' } : {}),

  projects: [
    // Smoke specs run WITHOUT authentication (test redirects, public pages).
    {
      name: 'smoke',
      testMatch: /smoke\/.*\.spec\.ts$/,
      use: { ...devices['Desktop Chrome'], storageState: { cookies: [], origins: [] } },
    },
    // Critical specs use the authenticated storage state (generated by globalSetup when present).
    {
      name: 'critical',
      testMatch: /critical\/.*\.spec\.ts$/,
      use: {
        ...devices['Desktop Chrome'],
        ...(hasGlobalSetup ? { storageState: STORAGE_STATE_PATH } : {}),
      },
    },
  ],

  // Starts the app automatically before the tests. CI uses the prod build (faster + more realistic);
  // local uses dev for hot-reload between runs.
  webServer: {
    command: isCI ? 'pnpm start' : 'pnpm dev',
    url: BASE_URL,
    reuseExistingServer: !isCI,
    timeout: 180_000,
    stdout: 'ignore',
    stderr: 'pipe',
  },
})
